  server:
    port: 8000
    servlet:
      context-path: /
      encoding:
        charset: UTF-8
        enabled: true
        force: true

  spring:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/mydb
      username: mtadmin
      password: cldn123

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 729559997185-a70l3ih2tk5l1b4ea091ldm1df8pk442.apps.googleusercontent.com
            client-secret: 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
            scope:
              -email
              -profile

          naver:
            client-id: p9PnJW3sKGYgnTw8PhqZ
            client-secret: neXlgV5hej
            scope:
              -name
              -email
              -profile_image

            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost8000/login/oauth2/code/naver

          provider:
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com.oauth2.0/token
              user-info-uri: https:openapi.naver.com/v1/nid/me
              user-name-attribute: response
